package T145.boom;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.block.state.IBlockState;
import net.minecraft.entity.item.EntityFallingBlock;
import net.minecraft.init.Blocks;
import net.minecraft.init.SoundEvents;
import net.minecraft.util.EnumParticleTypes;
import net.minecraft.util.SoundCategory;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.MathHelper;
import net.minecraft.world.Explosion;
import net.minecraft.world.World;
import net.minecraftforge.event.world.ExplosionEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.Mod.Metadata;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

@Mod(modid = RealisticExplosions.MODID, name = RealisticExplosions.NAME, version = RealisticExplosions.VERSION, updateJSON = RealisticExplosions.UPDATE_JSON)
@Mod.EventBusSubscriber(modid = RealisticExplosions.MODID)
public class RealisticExplosions {

	public static final String MODID = "realisticexplosions";
	public static final String NAME = "RealisticExplosions";
	public static final String VERSION = "@VERSION@";
	public static final String UPDATE_JSON = "https://raw.githubusercontent.com/T145/realistic-explosions/master/update.json";
	public static final Logger LOG = LogManager.getLogger(MODID);

	@Instance(MODID)
	public static RealisticExplosions instance;

	@Metadata
	private ModMetadata meta;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		meta.authorList.add("T145");
		meta.autogenerated = false;
		meta.credits = "The fans!";
		meta.description = "Here comes the BETTER BOOM!";
		meta.logoFile = "logo.png";
		meta.modId = MODID;
		meta.name = NAME;
		meta.url = "https://github.com/T145/realistic-explosions";
		meta.useDependencyInformation = false;
		meta.version = VERSION;
	}

	@SubscribeEvent
	public static void onExplosionStart(ExplosionEvent.Start event) {
		event.setCanceled(true);
		event.getExplosion().doExplosionA();
	}

	@SubscribeEvent
	public static void onExplosionDetonate(ExplosionEvent.Detonate event) {
		doExplosionB(event.getWorld(), event.getExplosion(), true);
	}

	private static void doExplosionB(World world, Explosion explosion, boolean spawnParticles) {
		world.playSound(null, explosion.x, explosion.y, explosion.z, SoundEvents.ENTITY_GENERIC_EXPLODE, SoundCategory.BLOCKS, 4.0F, (1.0F + (world.rand.nextFloat() - world.rand.nextFloat()) * 0.2F) * 0.7F);

		if (explosion.size >= 2.0F && explosion.damagesTerrain) {
			world.spawnParticle(EnumParticleTypes.EXPLOSION_HUGE, explosion.x, explosion.y, explosion.z, 1.0D, 0.0D, 0.0D);
		} else {
			world.spawnParticle(EnumParticleTypes.EXPLOSION_LARGE, explosion.x, explosion.y, explosion.z, 1.0D, 0.0D, 0.0D);
		}

		if (explosion.damagesTerrain) {
			for (BlockPos blockpos : explosion.affectedBlockPositions) {
				IBlockState state = world.getBlockState(blockpos);
				Block block = state.getBlock();

				if (spawnParticles) {
					double d0 = (double) ((float) blockpos.getX() + world.rand.nextFloat());
					double d1 = (double) ((float) blockpos.getY() + world.rand.nextFloat());
					double d2 = (double) ((float) blockpos.getZ() + world.rand.nextFloat());
					double d3 = d0 - explosion.x;
					double d4 = d1 - explosion.y;
					double d5 = d2 - explosion.z;
					double d6 = (double) MathHelper.sqrt(d3 * d3 + d4 * d4 + d5 * d5);
					d3 = d3 / d6;
					d4 = d4 / d6;
					d5 = d5 / d6;
					double d7 = 0.5D / (d6 / (double) explosion.size + 0.1D);
					d7 = d7 * (double) (world.rand.nextFloat() * world.rand.nextFloat() + 0.3F);
					d3 = d3 * d7;
					d4 = d4 * d7;
					d5 = d5 * d7;
					world.spawnParticle(EnumParticleTypes.EXPLOSION_NORMAL, (d0 + explosion.x) / 2.0D, (d1 + explosion.y) / 2.0D, (d2 + explosion.z) / 2.0D, d3, d4, d5);
					world.spawnParticle(EnumParticleTypes.SMOKE_NORMAL, d0, d1, d2, d3, d4, d5);
				}

				if (state.getMaterial() != Material.AIR) {
					if (block.canDropFromExplosion(explosion)) {
						//EntityFallingBlockOverride e = new EntityFallingBlockOverride(world, explosion.x, explosion.y, explosion.z, state);
						//e.fallTime = 65346;
						//e.setFallTile(state);
						EntityFallingBlock e = new EntityFallingBlock(world, explosion.x, explosion.y, explosion.z, state);
						//e.fallTime = 99;
						e.fallTime = 14;

						boolean b = world.rand.nextBoolean();
						float motionX = world.rand.nextFloat() * (b ? 1 : -1);
						float motionY = world.rand.nextFloat();
						b = world.rand.nextBoolean();
						float motionZ = world.rand.nextFloat() * (b ? 1 : -1);

						e.motionX = motionX;
						e.motionY = motionY;
						e.motionZ = motionZ;

						world.spawnEntity(e);
					}

					block.onBlockExploded(world, blockpos, explosion);
				}
			}
		}

		if (explosion.causesFire) {
			for (BlockPos blockpos1 : explosion.affectedBlockPositions) {
				if (world.getBlockState(blockpos1).getMaterial() == Material.AIR && world.getBlockState(blockpos1.down()).isFullBlock() && explosion.random.nextInt(3) == 0) {
					world.setBlockState(blockpos1, Blocks.FIRE.getDefaultState());
				}
			}
		}
	}
}